version: '3.8'

services:
  frontend:
    build:
      context: .
    volumes:
      - front:/app/build/  # Adjust if needed
    # command: ["npm", "run" ,"dev"]  # Ensure it starts your build process

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "80:80"
    volumes:
      - front:/var/www/propelo/frontend  # This should point to the build output
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

volumes:
  front:
