version: '3.8'

services:
  frontend:
    build:
      context: ./
    container_name: frontend_app
    ports:
      - "5173:5173"  # Expose Vite dev server on port 5173
    expose:
      - "5173"  # Expose Vite server internally for Nginx to access

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the Nginx container
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro  # Mount your custom Nginx config
    depends_on:
      - frontend  # Ensure Nginx starts after frontend
