version: '3.8'

services:
  frontend:
    build:
      context: .
    volumes:
      - front:/app/build/

  nginx:
    image: nginx:alpine
    container_name: frontend_nginx
    ports:
      - "80:80"
    volumes:
      - front:/var/www/propelo/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend


volumes:
  front: